export enum ConfigureEnum {
  REDIS_SESSION = 'REDIS_SESSION',
  REDIS_REGISTER = 'REDIS_REGISTER',
  REDIS_PREVENT_DOS_ATT = 'REDIS_PREVENT_DOS_ATT',
  REDIS_TMP_FILE = 'REDIS_TMP_FILE',
  REDIS_CACHE = 'REDIS_CACHE',
  REDIS_SEARCH_DATA = 'SEARCH_DATA',
  TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME',
  REDIS_CACHE_EXPIRE_TIME = 'REDIS_CACHE_EXPIRE_TIME',

  CRYPTO_SOLT = 'CRYPTO_SOLT',
  CRYPTO_SCERET = 'CRYPTO_SCERET',
}
