export enum ConfigureEnum {
  REDIS_SESSION = 'REDIS_SESSION',
  REDIS_REGISTER = 'REDIS_REGISTER',
  REDIS_PREVENT_DOS_ATT = 'REDIS_PREVENT_DOS_ATT',
  REDIS_TMP_FILE = 'REDIS_TMP_FILE',
  REDIS_CACHE = 'REDIS_CACHE',
  REDIS_SEARCH_DATA = 'SEARCH_DATA',
  TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME',
  REDIS_CACHE_EXPIRE_TIME = 'REDIS_CACHE_EXPIRE_TIME',

  CRYPTO_SOLT = 'CRYPTO_SOLT',
  CRYPTO_SCERET = 'CRYPTO_SCERET',

  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DB = 'DATABASE_DB',
  DATABASE_LOGGING = 'DATABASE_LOGGING',
  DATABASE_SYNCRONIZE = 'DATABASE_SYNCRONIZE',
}
