export enum ConfigureEnum {
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_DB = 'DATABASE_DB',
  DATABASE_LOGGING = 'DATABASE_LOGGING',
  DATABASE_SYNCRONIZE = 'DATABASE_SYNCRONIZE',
}
